import React from 'react';
import Panel from './panel';

export default () => {
  return <Panel>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tempus semper sem. Fusce vel ipsum pellentesque, faucibus nunc eget, rhoncus velit. Sed at magna ut purus vehicula viverra. In vehicula faucibus lorem, facilisis vulputate tortor dapibus quis. Maecenas ac sem velit. Quisque in tincidunt quam, a porta diam. Aenean lorem orci, iaculis a risus eu, sodales auctor mauris. Sed scelerisque accumsan est ac blandit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sagittis euismod odio vel dictum. Nam elementum magna id tellus molestie, vitae lobortis erat blandit. Donec consectetur sit amet orci et finibus. Nulla rhoncus tortor in libero pulvinar, id placerat augue lacinia. Maecenas convallis justo augue. Nulla facilisi. Nullam non risus sit amet nibh vulputate mollis eget ac dolor.</p>
    <p>Nullam at convallis magna. Cras maximus ligula ut turpis porttitor ultricies. Vestibulum pulvinar risus quis pellentesque bibendum. Vivamus dolor nunc, blandit iaculis urna non, molestie rhoncus orci. Duis dictum lorem id ante sagittis, maximus ultrices libero commodo. Quisque vulputate risus tellus, eget feugiat mi faucibus a. Aenean eu mi et nisi ultrices mattis. Donec id ornare dolor. Ut lectus eros, tincidunt nec dignissim id, pulvinar a erat. Mauris aliquet nisl non nibh gravida, eu dapibus libero placerat. Nam at quam eleifend, blandit ipsum et, hendrerit lectus. Quisque eget mauris vitae eros aliquet lacinia at et nisl.</p>
    <p>Nam pellentesque sapien eget lacinia luctus. Duis consequat turpis at lorem laoreet, ut rutrum purus bibendum. Aliquam erat volutpat. Sed ut nunc et nisi sagittis lacinia pretium non urna. Mauris in pellentesque nibh. Ut ac odio leo. Donec elementum eget tortor nec facilisis. Etiam convallis condimentum velit eget imperdiet. Vestibulum imperdiet, urna et tincidunt interdum, neque nibh rhoncus turpis, ac hendrerit tellus augue et lectus. Ut purus mi, iaculis eget odio vel, imperdiet dignissim elit.</p><p>Sed ac mi pulvinar, tincidunt felis eu, porta ipsum. Donec nec pretium est, quis ultricies lacus. Sed non neque eu eros tristique molestie at sit amet urna. Ut sit amet neque bibendum leo ornare vestibulum. Cras venenatis diam et enim viverra, ac placerat lacus aliquam. Cras varius mi est, at tempus felis iaculis vestibulum. In eget tincidunt libero. Phasellus id orci velit. Donec at lacus ut diam blandit volutpat. Aliquam finibus orci ut lacus gravida, vitae scelerisque tortor ultrices. Praesent sollicitudin erat metus, eu sodales libero fringilla non. Ut eget rhoncus eros, sit amet euismod ex.</p>
  </Panel>;
}
